### ISSUE TITLE
活动ws连接数是否过多？

### ISSUE THREAD

**Issue by shoucandanghehe** [dd-center/DDatHome-nodejs#115]
![image](https://user-images.githubusercontent.com/51957264/175800570-cbf434e6-863e-4d46-ab51-8c4231370d3e.png)

**Comment by shoucandanghehe** [comment]
图为运行三个半小时左右的连接 使用docker版
编辑：
![image](https://user-images.githubusercontent.com/51957264/175813606-8e5f60b6-3299-4bf3-8ecb-363043e1f05c.png)
十小时+

**Comment by simon300000** [comment]
哦哦 这个是可以通过env修改的LIMIT=123这样

**Comment by simon300000** [comment]
理论上会给每个直播间建立一个链接，也就是大概几千这个数字，因为这些弹幕流量其实很小就没有特别限制
