### ISSUE TITLE
API /x/space/acc/info 出现大量-401返回值

### ISSUE THREAD

**Issue by Radekyspec** [dd-center/DDatHome-nodejs#120]
最近b站给 https://api.bilibili.com/x/space/acc/info 加了反爬

被拦截的请求会返回 -401 非法访问

初步摸索到的解决方法：给请求加上有效的User-Agent和值不为空的Cookie

**Comment by simon300000** [comment]
相关 https://github.com/dd-center/vtbs.moe/issues/406

**Comment by simon300000** [comment]
相关 https://github.com/simon300000/bili-api/issues/153
