### ISSUE TITLE
建议直接编译成可执行文件供下载

### ISSUE THREAD

**Issue by shigma** [dd-center/DDatHome-nodejs#14]

**Comment by simon300000** [comment]
exe可以用带gui的 https://github.com/dd-center/DDatElectron
可执行可以用golang的 https://github.com/dd-center/DDatHome-go
而且我不会编译（

**Comment by shigma** [comment]
https://github.com/zeit/pkg

https://github.com/nexe/nexe

**Comment by simon300000** [comment]
咦，研究研究

**Comment by simon300000** [comment]
你觉得编译出来应该通过什么办法发布呀？

**Comment by simon300000** [comment]
https://github.com/dd-center/DDatHome-nodejs/releases/tag/v1.0.0
