### ISSUE TITLE
Use something like pws to reconnect to server

### ISSUE THREAD

**Issue by eight04** [dd-center/DDatHome-nodejs#2]
Currently, it relies on the `close` event and it doesn't detect [broken connection](https://www.npmjs.com/package/ws#how-to-detect-and-close-broken-connections). Sometimes it hangs when the connection is lost. It might be better to switch to something like [pws](https://www.npmjs.com/package/pws).

Since we have `DDDhttp`, we can set a [`pingTimeout`](https://github.com/porsager/pws/blob/52e9bbadba07627495968d926f5f4406e5547278/src/index.js#L186) to reconnect automatically.

**Comment by simon300000** [comment]
WOW!
I am having this question at DD@Electron, were connections are broken but does not reconnect, this tool should be able to solve that problem.

**Comment by simon300000** [comment]
I use ping timeout at client side now, it seems work
