### ISSUE TITLE
Pass options to the CLI

### ISSUE THREAD

**Issue by eight04** [dd-center/DDatHome-nodejs#4]
Currently, we have to set env variables for configuration:
```
cmd /c "SET VERBOSE=1 && SET INTERVAL=2000 && npx dd-center/DDatHome-nodejs"
```
It will be nice if we can pass them to the CLI directly:
```
npx dd-center/DDatHome-nodejs --verbose --interval 2000
```
I can file a PR using [neodoc](https://www.npmjs.com/package/neodoc) if you like.

**Comment by simon300000** [comment]
Thanks, a PR would be nice!
