### ISSUE TITLE
运行时弹出警告信息

### ISSUE THREAD

**Issue by DarkmatterUAE** [dd-center/DDatHome-nodejs#94]
运行ddathome-nodejs-1.8.1时报错。不影响运行。

Linux内核版本：v3.4.5
node版本：v14.15.0 （node16似乎无法正常运行？）
ddathome版本：v1.8.1

原始报错：
https://www.verybin.com/?5178f4dac81503ba#shRcaNFVrIAj1YUyKMTwZk0m/T2yEibpkBd1zSQ3PUw=

加入 --trace-warnings 后的报错：
https://www.verybin.com/?92953b7f0a6cfd02#GN5Z2e4S9Uf3zl45LabarCVc0MsZ/rx37K+kvqXkdqM=

**Comment by simon300000** [comment]
hum 我看看

**Comment by simon300000** [comment]
看看1.8.2是否修复了这个问题？

**Comment by DarkmatterUAE** [comment]
跑了一会，看起来是不会报错了。ok
